learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式。"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """用户学习的主题。"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	"""返回模型的字符串表示。"""
    	return self.text

class Entry(models.Model):
	"""学到的有关某个主题的具体知识。"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""返回模型的字符串表示"""
		text = self.text
		if len(self.text)>50:
			text = f"{self.text[:50]}..."
		return text

learning_logs/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	"""学习笔记的主页"""
	return render(request, 'learning_logs/index.html')

learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a>
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
<p>learning Log</p>

<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>